# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
sudo: false
dist: trusty
cache: packages

warnings_are_errors: false

env:
  global:
    - R_KEEP_PKG_SOURCE=yes
    - _R_S3_METHOD_LOOKUP_BASEENV_AFTER_GLOBALENV_=true
    - _R_S3_METHOD_LOOKUP_USE_TOPENV_AS_DEFENV_=true
    - _R_CHECK_FORCE_SUGGESTS=0

script:
  - export _R_CHECK_FORCE_SUGGESTS_=0
  - make travis
